<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="transportationlinemodel" nsURI="http://www.example.org/transportationlinemodel"
    nsPrefix="transportationlinemodel">
  <eClassifiers xsi:type="ecore:EClass" name="ItemGenerator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Area">
    <eStructuralFeatures xsi:type="ecore:EReference" name="itemgenerator" lowerBound="1"
        eType="#//ItemGenerator" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" upperBound="-1" eType="#//Item"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        upperBound="-1" eType="#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System">
    <eStructuralFeatures xsi:type="ecore:EReference" name="area" lowerBound="1" upperBound="-1"
        eType="#//Area" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hosts" eType="#//Item"
        eOpposite="#//Item/location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="neighbours" upperBound="-1"
        eType="#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isProcessed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" eType="#//Component"
        eOpposite="#//Component/hosts"/>
  </eClassifiers>
</ecore:EPackage>
